name: longevity-genie
channels:
  - conda-forge
  - bioconda
  - pytorch
  - plotly
  - defaults
dependencies:
  - python=3.10
  - more-itertools
  - setuptools
  - click
  - jupyterlab
  - jupyter
  - dash
  - dash-core-components
  - dash-table
  - dash-html-components
  - dash-bootstrap-components
  - uvicorn
  - dvc
  - pip:
      - pyfunctional
      - pycomfort>=0.0.14
      - pynction
      - polars
      - langchain>=0.0.323
      - qdrant-client>=1.6.1
      - google-search-results
      - indexpaper>=0.0.13
      - pyarrow
      - thefuzz
      - python-Levenshtein
      - sentence_transformers
      - longdata>=0.0.2