name: longevity-genie
channels:
  - conda-forge
  - bioconda
  - pytorch
  - plotly
  - defaults
dependencies:
  - python=3.10
  - more-itertools
  - setuptools
  - click
  - jupyterlab
  - jupyter
  - dash
  - dash-core-components
  - dash-table
  - dash-html-components
  - dash-bootstrap-components
  - uvicorn
  - dvc
  - pip:
      - pyfunctional
      - pynction
      - polars
      - langchain>=0.0.247
      - dvc_gdrive
      - pycomfort
      - google-search-results
      - indexpaper
      - pyarrow
      - thefuzz
      - python-Levenshtein
      - sentence_transformers